version: "3"

services:
  www:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vuepress
    ports:
      - "8080:8080"
    volumes:
      - ".:/workspace"
    command: yarn dev